"""
tools/create_bundle.py
----------------------
Creates the Codabench competition bundle (bundle.zip) from the repository.

Usage
-----
    cd <repo_root>
    python tools/create_bundle.py

The generated bundle.zip can be uploaded directly to:
    https://www.codabench.org/competitions/upload/

Bundle structure expected by Codabench
---------------------------------------
    competition.yaml
    logo.png
    requirements.txt
    ingestion_program/
        ingestion.py
        metadata.yaml
    scoring_program/
        scoring.py
        metadata.yaml
    solution/
        submission.py
    pages/
        overview.md
        data.md
        evaluation.md
        starting_kit.md
        terms.md
    dev_phase/
        input_data/
            X_train.csv
            X_test.csv
        reference_data/
            labels_public.csv
            labels_private.csv
"""

import os
import zipfile
import sys

# Files and folders to include in the bundle (relative to repo root)
INCLUDE = [
    "competition.yaml",
    "logo.png",
    "requirements.txt",
    "ingestion_program/ingestion.py",
    "ingestion_program/metadata.yaml",
    "scoring_program/scoring.py",
    "scoring_program/metadata.yaml",
    "solution/submission.py",
    "pages/participate.md",
    "pages/seed.md",
    "pages/timeline.md",
    "pages/terms.md",
    "pages/terms.md",
]

# Data directories — only included if they exist (generated by setup_data.py)
DATA_DIRS = [
    "dev_phase/input_data",
    "dev_phase/reference_data",
]

OUTPUT_BUNDLE = "bundle.zip"


def create_bundle(root="."):
    root = os.path.abspath(root)
    bundle_path = os.path.join(root, OUTPUT_BUNDLE)

    missing = [f for f in INCLUDE if not os.path.exists(os.path.join(root, f))]
    if missing:
        print("⚠️  Missing files (will be skipped):")
        for f in missing:
            print(f"    - {f}")

    data_missing = [d for d in DATA_DIRS
                    if not os.path.isdir(os.path.join(root, d))]
    if data_missing:
        print("\n⚠️  Data directories not found (run setup_data.py first):")
        for d in data_missing:
            print(f"    - {d}")
        print()

    with zipfile.ZipFile(bundle_path, "w", zipfile.ZIP_DEFLATED) as zf:
        # Static files
        for rel_path in INCLUDE:
            full = os.path.join(root, rel_path)
            if os.path.exists(full):
                zf.write(full, rel_path)
                print(f"  ✓ {rel_path}")

        # Data directories
        for data_dir in DATA_DIRS:
            full_dir = os.path.join(root, data_dir)
            if os.path.isdir(full_dir):
                for fname in os.listdir(full_dir):
                    full_file = os.path.join(full_dir, fname)
                    rel_file = os.path.join(data_dir, fname)
                    if os.path.isfile(full_file):
                        zf.write(full_file, rel_file)
                        print(f"  ✓ {rel_file}")

    size_mb = os.path.getsize(bundle_path) / 1e6
    print(f"\n✅ Bundle created: {bundle_path} ({size_mb:.1f} MB)")
    print(f"\nUpload it at: https://www.codabench.org/competitions/upload/")


if __name__ == "__main__":
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    create_bundle(repo_root)
